services:
  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: games
      TZ: Europe/Warsaw
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
    driver: local